name: Build MobileGlues for iOS
on: [push, workflow_dispatch]

permissions:
  actions: write
  contents: read

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build MobileGlues
        run: |
          cd MobileGlues-cpp
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake \
            -DSTATICLIB=OFF \
            -DMACOS=ON \
            -DPLATFORM=OS64 \
            -DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration
          cmake --build build --config RelWithDebInfo --target mobileglues
          codesign -s - build/libmobileglues.dylib

      - name: Delete old artifacts (Free up storage immediately)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Finding old artifacts named MobileGlues-iOS-dylib..."
          ARTIFACT_IDS=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.name == "MobileGlues-iOS-dylib") | .id')
          for id in $ARTIFACT_IDS; do
            echo "Deleting artifact ID: $id"
            gh api -X DELETE repos/${{ github.repository }}/actions/artifacts/$id
          done

      - name: Prepare artifact folder structure
        run: |
          mkdir -p staging/MobileGlues
          cp MobileGlues-cpp/build/libmobileglues.dylib staging/MobileGlues/

      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: MobileGlues-iOS-dylib
          path: staging
          retention-days: 1
