name: Build MobileGlues for iOS
on: [push, workflow_dispatch]

permissions:
  actions: write
  contents: read

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build MobileGlues
        run: |
          cd MobileGlues-cpp
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake \
            -DSTATICLIB=OFF \
            -DMACOS=ON \
            -DPLATFORM=OS64 \
            -DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration
          cmake --build build --config RelWithDebInfo --target mobileglues
          codesign -s - build/libmobileglues.dylib

      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: MobileGlues-iOS-dylib
          path: MobileGlues-cpp/build/libmobileglues.dylib
          retention-days: 1

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }} 
          retain_days: 0
          keep_minimum_runs: 1
